server:
  port: 8080

spring:
  application:
    name: product-management

  cache:
    type: simple

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product-management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_POSTGRES_PASSWORD:postgres}

  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: postgresql
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: drop

  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true
      schema-locations:
      - classpath:/schema.sql
      data-locations:
      - classpath:/data.sql